#!/bin/bash

function printUsageAndExit {
  echo "Retrieves a list of images in a Docker registry's repository."
  echo
  echo "Usage: $0 [-f|--full] [-l|--list] REPOSITORY" >&2
  exit 1
}

list="false"
printFullRepository="false"
while [[ $# -gt 0 ]]
do
  argument="$1"
  case ${argument} in
    -f|--full)
      printFullRepository="true"
      shift
      ;;
    -l|--list)
      list="true"
      shift
      ;;
    -*)
      echo "Unknown argument ${argument}" >&2
      printUsageAndExit
      ;;
    *)
      # Not an option, stop processing options
      break
      ;;
  esac
done

if [ $# -ne 1 ]; then
  printUsageAndExit
fi

repository=${1}
registry=$(echo ${repository} | cut -d'/' -f1 )
name=$(echo ${repository} | cut -d'/' -f2-)

for tag in $(curl -s -S http://${registry}/v2/${name}/tags/list | jq -r '.tags | join("\n")' | sort); do
  if [ "${printFullRepository}" = "true" ]; then
    echo ${repository}:${tag}
  else
    echo ${tag}
  fi
done | if [ "${list}" = "false" ]; then
  column
else
  cat
fi
